export const artistDistrictTagline = 'Discover incredible Nail Shops from creators around the world.';

export const livingCommunityMetrics = [
  { id: 'looks', title: 'Looks Shared', value: '318', subtitle: 'Today', icon: 'sparkles', accentColor: '#ff4fa3', liveStatus: true, trendText: '↑ 12% from yesterday' },
  { id: 'chrome', title: 'Trending', value: 'Chrome', subtitle: '124 new posts', icon: 'trending', accentColor: '#a980ff', liveStatus: true },
  { id: 'shops', title: 'New Nail Shops', value: '8', subtitle: 'This Week', icon: 'storefront', accentColor: '#35e3e4', liveStatus: false },
  { id: 'designs', title: 'Designs Created', value: '2.4K', subtitle: 'This Month', icon: 'brush', accentColor: '#f3c27c', liveStatus: true },
];

export const foundingShops = [
  {
    id: 'velvet-pedal',
    name: 'Velvet Petal Studio',
    category: 'Boutique Nail Atelier',
    specialty: 'Luxury Nail Studio',
    location: 'Atlanta, GA',
    rating: '4.9',
    designCount: '148',
    followerCount: '12.8K',
    storefrontImage: '/assets/founding-shops/velvet-pedal/velvet-petal-cover.png',
    storefrontAlt: 'The illuminated Velvet Petal Studio storefront at dusk',
    signatureNailImage: '/assets/founding-shops/velvet-pedal/velvet-petal-signature-nail.png',
    signatureNailAlt: 'Velvet Petal Studio signature sculpted floral nail',
    ctaDestination: null,
    accent: '#ef6aa8',
  },
  {
    id: 'kikis-nail-shop',
    name: "Kiki's Nail Shop",
    category: 'Contemporary Nail Bar',
    specialty: 'Hand-Painted Art',
    location: 'Chicago, IL',
    rating: '4.8',
    designCount: '126',
    followerCount: '9.6K',
    storefrontImage: '/assets/founding-shops/kikis-nail-shop/kikis-shop-cover.png',
    storefrontAlt: "Kiki's Nail Shop storefront with its colorful boutique signage",
    signatureNailImage: '/assets/founding-shops/kikis-nail-shop/kikis-signature-nail.png',
    signatureNailAlt: "Kiki's Nail Shop signature hand-painted nail design",
    ctaDestination: null,
    accent: '#f2a7ca',
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour Nails',
    category: 'Sunlit Nail Atelier',
    specialty: 'Chrome Specialist',
    location: 'Los Angeles, CA',
    rating: '4.9',
    designCount: '174',
    followerCount: '15.2K',
    storefrontImage: '/assets/founding-shops/golden-hour/golden-hour-cover.png',
    storefrontAlt: 'Golden Hour Nails storefront glowing in warm sunset light',
    signatureNailImage: '/assets/founding-shops/golden-hour/golden-hour-signature-nail.png',
    signatureNailAlt: 'Golden Hour Nails signature luminous gold nail',
    ctaDestination: null,
    accent: '#e9b760',
  },
  {
    id: 'cherry-lacquer',
    name: 'Cherry Lacquer Loft',
    category: 'Editorial Nail Loft',
    specialty: 'Editorial Nail Art',
    location: 'Brooklyn, NY',
    rating: '4.9',
    designCount: '163',
    followerCount: '13.4K',
    storefrontImage: '/assets/founding-shops/cherry-lacquer/cherry-lacquer-cover.png',
    storefrontAlt: 'Cherry Lacquer Loft storefront with deep red illuminated signage',
    signatureNailImage: '/assets/founding-shops/cherry-lacquer/cherry-lacquer-signature-nail.png',
    signatureNailAlt: 'Cherry Lacquer Loft signature deep cherry nail',
    ctaDestination: null,
    accent: '#e45b68',
  },
  {
    id: 'azure-tide',
    name: 'Azure Tide',
    category: 'Coastal Nail Studio',
    specialty: 'Coastal Nail Design',
    location: 'Miami, FL',
    rating: '4.8',
    designCount: '119',
    followerCount: '8.9K',
    storefrontImage: '/assets/founding-shops/azure-tide/azure-tide-cover.png',
    storefrontAlt: 'Azure Tide coastal nail studio storefront in ocean-blue light',
    signatureNailImage: '/assets/founding-shops/azure-tide/azure-tide-signature-nail.png',
    signatureNailAlt: 'Azure Tide signature ocean-inspired blue nail',
    ctaDestination: null,
    accent: '#55c9db',
  },
];

export const foundingArtists = [
  {
    artistId: 'lani-petal', artistName: 'Lani Petal', shopName: 'Velvet Petal Studio', location: 'Atlanta, GA', specialty: 'Luxury Floral Art',
    shortBio: 'Romantic sets, sculpted florals, and polished details designed with softness and precision.',
    portraitImage: '/assets/founding-artists/velvet-petal/velvet-petal-artist.png', portraitAlt: 'Lani Petal standing in the bright pink-and-gold Velvet Petal Studio.',
    accent: '#ef7da9', statusLabel: 'Rising Artist', ctaLabel: 'Meet the Artist', ctaDestination: null,
  },
  {
    artistId: 'ki-ki', artistName: 'Ki Ki', shopName: "Kiki's Nail Shop", location: 'Chicago, IL', specialty: 'Hand-Painted Art',
    shortBio: 'Bold color, expressive brushwork, and joyful designs made for clients who refuse to blend in.',
    portraitImage: '/assets/founding-artists/kikis-nail-shop/kikis-artist.png', portraitAlt: "Ki Ki standing inside Kiki's colorful nail studio.",
    accent: '#46d6cf', statusLabel: 'Color Storyteller', ctaLabel: 'Meet the Artist', ctaDestination: null,
  },
  {
    artistId: 'jae-luxe', artistName: 'Jae Luxe', shopName: 'Golden Hour Nails', location: 'Los Angeles, CA', specialty: 'Precision Luxury',
    shortBio: 'Refined technique, timeless finishes, and meticulous artistry shaped by years of experience.',
    portraitImage: '/assets/founding-artists/golden-hour/golden-hour-artist.png', portraitAlt: 'Jae Luxe standing in the warmly lit Golden Hour Nails studio.',
    accent: '#e4b965', statusLabel: 'Master Detailist', ctaLabel: 'Meet the Artist', ctaDestination: null,
  },
  {
    artistId: 'cherry-vale', artistName: 'Cherry Vale', shopName: 'Cherry Lacquer Loft', location: 'Brooklyn, NY', specialty: 'Gothic Acrylic Art',
    shortBio: 'Dark glamour, sculpted acrylics, and rebellious detail for clients who treat nails like armor.',
    portraitImage: '/assets/founding-artists/cherry-lacquer/cherry-lacquer-artist.png', portraitAlt: 'Cherry Vale standing in the deep red Cherry Lacquer Loft studio.',
    accent: '#d55469', statusLabel: 'Rockstar Artist', ctaLabel: 'Meet the Artist', ctaDestination: null,
  },
  {
    artistId: 'marisol-tide', artistName: 'Marisol Tide', shopName: 'Azure Tide', location: 'Miami, FL', specialty: 'Coastal Gel-X',
    shortBio: 'Airy ocean-inspired sets, modern color stories, and relaxed coastal luxury with a youthful edge.',
    portraitImage: '/assets/founding-artists/azure-tide/azure-tide-artist.png', portraitAlt: 'Marisol Tide standing in the sea-blue Azure Tide nail studio.',
    accent: '#58d5d0', statusLabel: 'Fresh Perspective', ctaLabel: 'Meet the Artist', ctaDestination: null,
  },
];

export const weeklyTrends = [
  { id: 'chrome-bloom', rank: 1, title: 'Chrome Bloom', shopName: 'Velvet Petal Studio', momentum: '↑ 38% this week', category: 'Floral', collectionImage: '/assets/founding-shops/velvet-pedal/velvet-bloom-collection.png', collectionAlt: 'Velvet Petal Studio floral nail collection in sculpted pink and chrome finishes', ctaDestination: null },
  { id: 'sunset-marble', rank: 2, title: 'Sunset Marble', shopName: 'Golden Hour Nails', momentum: 'Most Saved', category: 'Chrome', collectionImage: '/assets/founding-shops/golden-hour/golden-hour-collection.png', collectionAlt: 'Golden Hour Nails collection with luminous sunset-inspired chrome nail looks', ctaDestination: null },
  { id: 'pearl-luxe', rank: 3, title: 'Pearl Luxe', shopName: "Kiki's Nail Shop", momentum: 'Trending Now', category: 'Luxury', collectionImage: '/assets/founding-shops/kikis-nail-shop/kikis-featured-collection.png', collectionAlt: "Kiki's Nail Shop collection of detailed pearl and hand-painted nail looks", ctaDestination: null },
  { id: 'tropical-escape', rank: 4, title: 'Tropical Escape', shopName: 'Azure Tide', momentum: 'Community Favorite', category: 'Gel-X', collectionImage: '/assets/founding-shops/azure-tide/azure-tide-collection.png', collectionAlt: 'Azure Tide collection of ocean-blue and tropical-inspired nail looks', ctaDestination: null },
  { id: 'velvet-petals', rank: 5, title: 'Velvet Petals', shopName: 'Cherry Lacquer Loft', momentum: '↑ 24% this week', category: 'Editorial', collectionImage: '/assets/founding-shops/cherry-lacquer/cherry-lacquer-collection.png', collectionAlt: 'Cherry Lacquer Loft collection of deep red editorial nail looks', ctaDestination: null },
];

export const artistDistrictSections = [
  {
    id: 'featured-nail-shops',
    title: 'Featured Nail Shops',
    eyebrow: 'Curated by Headquarters',
    accent: 'pink',
    shops: foundingShops,
  },
  {
    id: 'trending-this-week',
    title: 'Trending This Week',
    eyebrow: 'The weekly edit',
    accent: 'teal',
    shops: weeklyTrends,
  },
  {
    id: 'new-artists',
    title: 'New Artists',
    eyebrow: 'Fresh Faces',
    description: 'Meet the artists bringing fresh perspective, personality, and craft to Artist District.',
    accent: 'violet',
    shops: foundingArtists,
  },
  {
    id: 'browse-all-nail-shops',
    title: 'Browse All Nail Shops',
    eyebrow: 'The district directory',
    description: 'Wander the storefronts and find the studio that catches your eye next.',
    accent: 'gold',
    shops: foundingShops,
  },
];
