export const artistDistrictTagline = 'Discover incredible Nail Shops from creators around the world.';

export const livingCommunityMetrics = [
  { id: 'looks', title: 'Looks Shared', value: '318', subtitle: 'Today', icon: 'sparkles', accentColor: '#ff4fa3', liveStatus: true, trendText: '↑ 12% from yesterday' },
  { id: 'chrome', title: 'Trending', value: 'Chrome', subtitle: '124 new posts', icon: 'trending', accentColor: '#a980ff', liveStatus: true },
  { id: 'shops', title: 'New Nail Shops', value: '8', subtitle: 'This Week', icon: 'storefront', accentColor: '#35e3e4', liveStatus: false },
  { id: 'designs', title: 'Designs Created', value: '2.4K', subtitle: 'This Month', icon: 'brush', accentColor: '#f3c27c', liveStatus: true },
];

export const foundingShops = [
  {
    id: 'velvet-pedal',
    name: 'Velvet Petal Studio',
    category: 'Boutique Nail Atelier',
    specialty: 'Luxury Nail Studio',
    location: 'Atlanta, GA',
    rating: '4.9',
    designCount: '148',
    followerCount: '12.8K',
    storefrontImage: '/assets/founding-shops/velvet-pedal/velvet-petal-cover.png',
    storefrontAlt: 'The illuminated Velvet Petal Studio storefront at dusk',
    signatureNailImage: '/assets/founding-shops/velvet-pedal/velvet-petal-signature-nail.png',
    signatureNailAlt: 'Velvet Petal Studio signature sculpted floral nail',
    ctaDestination: null,
    accent: '#ef6aa8',
  },
  {
    id: 'kikis-nail-shop',
    name: "Kiki's Nail Shop",
    category: 'Contemporary Nail Bar',
    specialty: 'Hand-Painted Art',
    location: 'Chicago, IL',
    rating: '4.8',
    designCount: '126',
    followerCount: '9.6K',
    storefrontImage: '/assets/founding-shops/kikis-nail-shop/kikis-shop-cover.png',
    storefrontAlt: "Kiki's Nail Shop storefront with its colorful boutique signage",
    signatureNailImage: '/assets/founding-shops/kikis-nail-shop/kikis-signature-nail.png',
    signatureNailAlt: "Kiki's Nail Shop signature hand-painted nail design",
    ctaDestination: null,
    accent: '#f2a7ca',
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour Nails',
    category: 'Sunlit Nail Atelier',
    specialty: 'Chrome Specialist',
    location: 'Los Angeles, CA',
    rating: '4.9',
    designCount: '174',
    followerCount: '15.2K',
    storefrontImage: '/assets/founding-shops/golden-hour/golden-hour-cover.png',
    storefrontAlt: 'Golden Hour Nails storefront glowing in warm sunset light',
    signatureNailImage: '/assets/founding-shops/golden-hour/golden-hour-signature-nail.png',
    signatureNailAlt: 'Golden Hour Nails signature luminous gold nail',
    ctaDestination: null,
    accent: '#e9b760',
  },
  {
    id: 'cherry-lacquer',
    name: 'Cherry Lacquer Loft',
    category: 'Editorial Nail Loft',
    specialty: 'Editorial Nail Art',
    location: 'Brooklyn, NY',
    rating: '4.9',
    designCount: '163',
    followerCount: '13.4K',
    storefrontImage: '/assets/founding-shops/cherry-lacquer/cherry-lacquer-cover.png',
    storefrontAlt: 'Cherry Lacquer Loft storefront with deep red illuminated signage',
    signatureNailImage: '/assets/founding-shops/cherry-lacquer/cherry-lacquer-signature-nail.png',
    signatureNailAlt: 'Cherry Lacquer Loft signature deep cherry nail',
    ctaDestination: null,
    accent: '#e45b68',
  },
  {
    id: 'azure-tide',
    name: 'Azure Tide',
    category: 'Coastal Nail Studio',
    specialty: 'Coastal Nail Design',
    location: 'Miami, FL',
    rating: '4.8',
    designCount: '119',
    followerCount: '8.9K',
    storefrontImage: '/assets/founding-shops/azure-tide/azure-tide-cover.png',
    storefrontAlt: 'Azure Tide coastal nail studio storefront in ocean-blue light',
    signatureNailImage: '/assets/founding-shops/azure-tide/azure-tide-signature-nail.png',
    signatureNailAlt: 'Azure Tide signature ocean-inspired blue nail',
    ctaDestination: null,
    accent: '#55c9db',
  },
];

export const weeklyTrends = [
  { id: 'chrome-bloom', rank: 1, title: 'Chrome Bloom', shopName: 'Velvet Petal Studio', momentum: '↑ 38% this week', category: 'Floral', collectionImage: '/assets/founding-shops/velvet-pedal/velvet-bloom-collection.png', collectionAlt: 'Velvet Petal Studio floral nail collection in sculpted pink and chrome finishes', ctaDestination: null },
  { id: 'sunset-marble', rank: 2, title: 'Sunset Marble', shopName: 'Golden Hour Nails', momentum: 'Most Saved', category: 'Chrome', collectionImage: '/assets/founding-shops/golden-hour/golden-hour-collection.png', collectionAlt: 'Golden Hour Nails collection with luminous sunset-inspired chrome nail looks', ctaDestination: null },
  { id: 'pearl-luxe', rank: 3, title: 'Pearl Luxe', shopName: "Kiki's Nail Shop", momentum: 'Trending Now', category: 'Luxury', collectionImage: '/assets/founding-shops/kikis-nail-shop/kikis-featured-collection.png', collectionAlt: "Kiki's Nail Shop collection of detailed pearl and hand-painted nail looks", ctaDestination: null },
  { id: 'tropical-escape', rank: 4, title: 'Tropical Escape', shopName: 'Azure Tide', momentum: 'Community Favorite', category: 'Gel-X', collectionImage: '/assets/founding-shops/azure-tide/azure-tide-collection.png', collectionAlt: 'Azure Tide collection of ocean-blue and tropical-inspired nail looks', ctaDestination: null },
  { id: 'velvet-petals', rank: 5, title: 'Velvet Petals', shopName: 'Cherry Lacquer Loft', momentum: '↑ 24% this week', category: 'Editorial', collectionImage: '/assets/founding-shops/cherry-lacquer/cherry-lacquer-collection.png', collectionAlt: 'Cherry Lacquer Loft collection of deep red editorial nail looks', ctaDestination: null },
];

export const artistDistrictSections = [
  {
    id: 'featured-nail-shops',
    title: 'Featured Nail Shops',
    eyebrow: 'Curated by Headquarters',
    accent: 'pink',
    shops: foundingShops,
  },
  {
    id: 'trending-this-week',
    title: 'Trending This Week',
    eyebrow: 'The weekly edit',
    accent: 'teal',
    shops: weeklyTrends,
  },
  {
    id: 'new-artists',
    title: 'New Artists',
    eyebrow: 'Fresh doors opening',
    accent: 'violet',
    shops: [
      { name: 'Moonlit Mani House', location: 'Seattle, WA', initials: 'MM', signature: 'Signature Nail™: Midnight Star', description: 'Starry accents and dimensional shimmer for midnight-inspired sets.', tags: ['Celestial Art', 'Velvet Cat Eye', 'Navy Chrome'] },
      { name: 'Peony Press Nails', location: 'Portland, OR', initials: 'PP', signature: 'Signature Nail™: Pressed Petal', description: 'Pressed-petal designs layered over creamy wearable shapes.', tags: ['Pressed Florals', 'Cream Base', 'Micro French'] },
      { name: 'Studio Maraschino', location: 'Miami, FL', initials: 'SM', signature: 'Signature Nail™: Cherry Vinyl', description: 'Juicy cherry palettes with playful charms and glossy overlays.', tags: ['Cherry Tones', 'Gloss Gel', 'Tiny Charms'] },
    ],
  },
  {
    id: 'browse-all-nail-shops',
    title: 'Browse All Nail Shops',
    eyebrow: 'The district directory',
    accent: 'gold',
    shops: [
      { name: 'Pearl Circuit Nails', location: 'Denver, CO', initials: 'PC', signature: 'Signature Nail™: Pearl Circuit', description: 'Pearl chrome lines and future-soft overlays for everyday statement sets.', tags: ['Pearl Chrome', 'Linework', 'Short Gel'] },
      { name: 'Glass Garden Studio', location: 'Savannah, GA', initials: 'GG', signature: 'Signature Nail™: Glass Bloom', description: 'Transparent botanicals, glassy layers, and light-catching garden color.', tags: ['Jelly Layers', 'Botanical', 'Clear Gel'] },
      { name: 'Opal Archive', location: 'Phoenix, AZ', initials: 'OA', signature: 'Signature Nail™: Opal File', description: 'Opalescent archives translated into soft sculpted modern sets.', tags: ['Opal Dust', 'Sculpted', 'Iridescent'] },
      { name: 'Ink & Alloy Nails', location: 'Detroit, MI', initials: 'IA', signature: 'Signature Nail™: Alloy Ink', description: 'Graphic ink details paired with molten silver chrome accents.', tags: ['Graphic Art', 'Silver Chrome', 'Gel Art'] },
      { name: 'Blush Voltage', location: 'Nashville, TN', initials: 'BV', signature: 'Signature Nail™: Blush Bolt', description: 'Electric blush details and glossy power color for stage-ready hands.', tags: ['Blush Pink', 'Lightning', 'Gloss'] },
      { name: 'Mink Mirror Room', location: 'New York, NY', initials: 'MR', signature: 'Signature Nail™: Mink Mirror', description: 'Reflective mink, smoky neutrals, and premium mirror-finish edits.', tags: ['Mirror Chrome', 'Neutral', 'Editorial'] },
    ],
  },
];
