import { COLORS, S } from "../styles.js";

export const UI = {
  shell: { height: "100%", minHeight: 0, display: "flex", flexDirection: "column", background: COLORS.bg },
  toolbar: { display: "flex", alignItems: "center", gap: 8, padding: "12px 18px", borderBottom: `1px solid ${COLORS.border}`, background: COLORS.surface, flexWrap: "wrap" },
  artistCommandBar: { display: "grid", gridTemplateColumns: "minmax(250px, 1.1fr) minmax(260px, .9fr) minmax(420px, 1.35fr)", gap: 22, alignItems: "center", padding: "26px 30px", borderBottom: "1px solid rgba(123,47,89,.14)", background: "linear-gradient(135deg, #fffaf7 0%, #fff 48%, #fff4fb 100%)", boxShadow: "0 18px 45px rgba(60,20,50,.08)", flexWrap: "wrap" },
  commandIdentity: { minWidth: 0 },
  commandLogo: { fontFamily: "Georgia, serif", fontSize: 18, letterSpacing: ".16em", textTransform: "uppercase", color: COLORS.plum, fontWeight: 800, marginBottom: 10 },
  commandDesignName: { width: "100%", border: 0, outline: 0, background: "transparent", color: COLORS.text, fontFamily: "Georgia, serif", fontSize: 36, lineHeight: 1.05, fontWeight: 700, padding: "2px 0", minWidth: 0 },
  commandCollection: { marginTop: 6, color: COLORS.textMuted, fontSize: 13, letterSpacing: ".18em", textTransform: "uppercase", fontWeight: 800 },
  commandCenter: { display: "flex", alignItems: "center", justifyContent: "center", gap: 16, minWidth: 0, flexWrap: "wrap" },
  autoSaveBadge: { border: "1px solid rgba(123,47,89,.14)", background: "rgba(255,255,255,.78)", borderRadius: 999, padding: "12px 16px", fontSize: 13, fontWeight: 900, letterSpacing: ".08em", textTransform: "uppercase", boxShadow: "0 10px 24px rgba(60,20,50,.07)" },
  currentPolishButton: { display: "flex", alignItems: "center", gap: 10, minHeight: 58, border: "1px solid rgba(123,47,89,.18)", background: "#fff", color: COLORS.text, borderRadius: 20, padding: "9px 14px", cursor: "pointer", boxShadow: "0 14px 34px rgba(60,20,50,.1)" },
  currentPolishText: { display: "flex", flexDirection: "column", gap: 2, fontSize: 12, fontWeight: 900, letterSpacing: ".06em", textTransform: "uppercase", textAlign: "left" },
  currentPolishMeta: { color: COLORS.textMuted, fontSize: 11, letterSpacing: ".02em", textTransform: "none" },
  commandActions: { display: "flex", justifyContent: "flex-end", alignItems: "center", gap: 10, flexWrap: "wrap" },
  commandButton: (active = false, disabled = false) => ({ border: `1px solid ${active ? COLORS.plum : "rgba(123,47,89,.18)"}`, background: active ? COLORS.roseDim : "rgba(255,255,255,.88)", color: disabled ? COLORS.textFaint : active ? COLORS.plum : COLORS.text, borderRadius: 16, minHeight: 48, padding: "12px 16px", fontSize: 13, fontWeight: 900, cursor: disabled ? "not-allowed" : "pointer", opacity: disabled ? 0.55 : 1, boxShadow: "0 10px 24px rgba(60,20,50,.06)" }),
  zoomPill: { display: "flex", alignItems: "center", gap: 8, minHeight: 48, padding: "6px 8px", borderRadius: 18, border: "1px solid rgba(123,47,89,.18)", background: "#fff", color: COLORS.plum, fontWeight: 900, boxShadow: "0 10px 24px rgba(60,20,50,.06)" },
  zoomButton: { width: 38, height: 36, border: 0, borderRadius: 12, background: COLORS.roseDim, color: COLORS.plum, fontSize: 18, fontWeight: 900, cursor: "pointer" },
  canvasModeButton: { minHeight: 52, border: "1px solid rgba(59,31,53,.28)", borderRadius: 18, padding: "12px 18px", color: "#fff", background: "linear-gradient(135deg, #3B1F35, #7B2F59)", fontSize: 13, fontWeight: 900, letterSpacing: ".1em", textTransform: "uppercase", cursor: "pointer", boxShadow: "0 16px 34px rgba(60,20,50,.2)" },
  layout: {
    flex: 1,
    minHeight: 0,
    display: "grid",
    gridTemplateColumns: "minmax(240px, 0.82fr) minmax(380px, 1.35fr) minmax(250px, 0.82fr)",
    gap: 10,
    padding: 10,
    overflow: "auto",
    alignItems: "start",
  },
  panel: { background: COLORS.surface, border: `1px solid ${COLORS.border}`, borderRadius: 18, boxShadow: "0 10px 30px rgba(60,20,50,.06)", minHeight: 0, minWidth: 0, overflow: "auto" },
  stickyPreview: { position: "sticky", top: 10, zIndex: 2, background: COLORS.surface },
  panelPad: { padding: 14 },
  sectionTitle: { fontSize: 12, letterSpacing: ".08em", textTransform: "uppercase", color: COLORS.textMuted, fontWeight: 800, marginBottom: 10 },
  miniButton: (active = false) => ({ ...(active ? S.btnSecondary : S.btnGhost), padding: "8px 10px", fontSize: 12, borderColor: active ? COLORS.plum : COLORS.border, color: active ? COLORS.plum : COLORS.textMuted, whiteSpace: "nowrap" }),
  panelSection: { border: `1px solid ${COLORS.border}`, borderRadius: 16, marginBottom: 12, background: "#fff", overflow: "hidden" },
  panelHeader: { width: "100%", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, padding: "10px 12px", border: 0, borderBottom: `1px solid ${COLORS.border}`, background: COLORS.roseDim, cursor: "pointer" },
  panelBody: { padding: 12 },
  actionGrid: { display: "grid", gridTemplateColumns: "repeat(4, minmax(42px, 1fr))", gap: 6, alignItems: "stretch" },
  iconOnlyButton: (active = false, disabled = false) => ({ border: `1px solid ${active ? COLORS.plum : COLORS.border}`, background: active ? COLORS.roseDim : "#fff", color: disabled ? COLORS.textFaint : active ? COLORS.plum : COLORS.text, borderRadius: 10, padding: "7px 8px", minHeight: 34, fontSize: 15, fontWeight: 800, cursor: disabled ? "not-allowed" : "pointer", opacity: disabled ? 0.55 : 1 }),
  iconButton: (active = false, disabled = false) => ({ border: `1px solid ${active ? COLORS.plum : COLORS.border}`, background: active ? COLORS.roseDim : "#fff", color: disabled ? COLORS.textFaint : active ? COLORS.plum : COLORS.text, borderRadius: 10, padding: "8px 10px", fontSize: 12, fontWeight: 700, cursor: disabled ? "not-allowed" : "pointer", opacity: disabled ? 0.55 : 1 }),
  field: { marginBottom: 14 },
  row: { display: "flex", gap: 8, alignItems: "center" },
  smallText: { fontSize: 12, color: COLORS.textMuted, lineHeight: 1.35 },
};
