import { COLORS, S } from "../styles.js";

export const UI = {
  shell: { height: "100dvh", maxHeight: "100dvh", minHeight: 0, display: "flex", flexDirection: "column", background: COLORS.bg, overflow: "hidden" },
  toolbar: { display: "flex", alignItems: "center", gap: 8, padding: "12px 18px", borderBottom: `1px solid ${COLORS.border}`, background: COLORS.surface, flexWrap: "wrap" },
  layout: {
    flex: 1,
    minHeight: 0,
    display: "grid",
    gridTemplateColumns: "minmax(240px, 0.82fr) minmax(380px, 1.35fr) minmax(250px, 0.82fr)",
    gap: 10,
    padding: 10,
    overflow: "hidden",
    alignItems: "stretch",
  },
  panel: { background: COLORS.surface, border: `1px solid ${COLORS.border}`, borderRadius: 18, boxShadow: "0 10px 30px rgba(60,20,50,.06)", height: "100%", minHeight: 0, minWidth: 0, overflow: "auto" },
  canvasPanel: { display: "flex", flexDirection: "column", alignItems: "stretch", height: "100%", minHeight: 0, overflow: "hidden" },
  canvasStage: { flex: "1 1 auto", minHeight: 0, display: "flex", alignItems: "center", justifyContent: "center", overflow: "auto", background: COLORS.surface },
  setPreview: { flex: "0 0 auto", maxHeight: "32%", overflow: "auto", borderTop: `1px solid ${COLORS.border}`, padding: "10px 14px", background: "#fff" },
  stickyPreview: { background: COLORS.surface },
  panelPad: { padding: 14 },
  sectionTitle: { fontSize: 12, letterSpacing: ".08em", textTransform: "uppercase", color: COLORS.textMuted, fontWeight: 800, marginBottom: 10 },
  miniButton: (active = false) => ({ ...(active ? S.btnSecondary : S.btnGhost), padding: "8px 10px", fontSize: 12, borderColor: active ? COLORS.plum : COLORS.border, color: active ? COLORS.plum : COLORS.textMuted, whiteSpace: "nowrap" }),
  panelSection: { border: `1px solid ${COLORS.border}`, borderRadius: 16, marginBottom: 12, background: "#fff", overflow: "hidden" },
  panelHeader: { width: "100%", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, padding: "10px 12px", border: 0, borderBottom: `1px solid ${COLORS.border}`, background: COLORS.roseDim, cursor: "pointer" },
  panelBody: { padding: 12 },
  actionGrid: { display: "grid", gridTemplateColumns: "repeat(4, minmax(42px, 1fr))", gap: 6, alignItems: "stretch" },
  iconOnlyButton: (active = false, disabled = false) => ({ border: `1px solid ${active ? COLORS.plum : COLORS.border}`, background: active ? COLORS.roseDim : "#fff", color: disabled ? COLORS.textFaint : active ? COLORS.plum : COLORS.text, borderRadius: 10, padding: "7px 8px", minHeight: 34, fontSize: 15, fontWeight: 800, cursor: disabled ? "not-allowed" : "pointer", opacity: disabled ? 0.55 : 1 }),
  iconButton: (active = false, disabled = false) => ({ border: `1px solid ${active ? COLORS.plum : COLORS.border}`, background: active ? COLORS.roseDim : "#fff", color: disabled ? COLORS.textFaint : active ? COLORS.plum : COLORS.text, borderRadius: 10, padding: "8px 10px", fontSize: 12, fontWeight: 700, cursor: disabled ? "not-allowed" : "pointer", opacity: disabled ? 0.55 : 1 }),
  field: { marginBottom: 14 },
  row: { display: "flex", gap: 8, alignItems: "center" },
  smallText: { fontSize: 12, color: COLORS.textMuted, lineHeight: 1.35 },
};
