import { COLORS, S } from "../styles.js";

const LUXURY_TRANSITION = "transform 180ms ease, box-shadow 180ms ease, border-color 180ms ease, background 180ms ease, color 180ms ease, opacity 180ms ease";

// command popovers share a fixed high z-index layer so quick controls are never clipped by the workspace.
// commandPolishPopover and commandFrenchTipPopover keep quick controls away from the hero canvas.
export const UI = {
  shell: {
    height: "100%",
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    background: COLORS.bg,
  },
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "12px 18px",
    borderBottom: `1px solid ${COLORS.border}`,
    background: COLORS.surface,
    flexWrap: "wrap",
  },
  artistCommandBar: {
    display: "grid",
    gridTemplateColumns:
      "minmax(0, 1.1fr) minmax(220px, .9fr) minmax(300px, 1.35fr)",
    width: "100%",
    maxWidth: "100%",
    boxSizing: "border-box",
    overflowX: "clip",
    gap: 22,
    alignItems: "center",
    padding: "clamp(14px, 2vw, 26px) clamp(16px, 2.4vw, 30px)",
    borderBottom: "1px solid rgba(123,47,89,.14)",
    background: "linear-gradient(135deg, #fffaf7 0%, #fff 48%, #fff4fb 100%)",
    boxShadow: "0 18px 45px rgba(60,20,50,.08)",
    flexWrap: "wrap",
  },
  commandIdentity: { minWidth: 0, maxWidth: "100%" },
  commandLogo: {
    fontFamily: "Georgia, serif",
    fontSize: 18,
    letterSpacing: ".16em",
    textTransform: "uppercase",
    color: COLORS.plum,
    fontWeight: 800,
    marginBottom: 10,
  },
  commandDesignName: {
    width: "100%",
    maxWidth: "100%",
    border: 0,
    outline: 0,
    background: "transparent",
    color: COLORS.text,
    fontFamily: "Georgia, serif",
    fontSize: "clamp(18px, 3.4vw, 34px)",
    lineHeight: 1.12,
    fontWeight: 700,
    padding: "2px 0",
    minWidth: 0,
    whiteSpace: "normal",
    overflow: "visible",
    overflowWrap: "anywhere",
    wordBreak: "break-word",
    textOverflow: "clip",
  },
  commandDesignNameCounter: {
    marginTop: 4,
    color: COLORS.textMuted,
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: ".08em",
    textTransform: "uppercase",
    textAlign: "right",
  },
  commandCollection: {
    marginTop: 6,
    color: COLORS.textMuted,
    fontSize: 13,
    letterSpacing: ".18em",
    textTransform: "uppercase",
    fontWeight: 800,
  },
  commandCenter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    minWidth: 0,
    flexWrap: "wrap",
  },
  autoSaveBadge: {
    border: "1px solid rgba(123,47,89,.14)",
    background: "rgba(255,255,255,.78)",
    borderRadius: 999,
    padding: "12px 16px",
    fontSize: 13,
    fontWeight: 900,
    letterSpacing: ".08em",
    textTransform: "uppercase",
    boxShadow: "0 10px 24px rgba(60,20,50,.07)",
    transition: LUXURY_TRANSITION,
  },
  currentPolishButton: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    minHeight: 58,
    border: "1px solid rgba(123,47,89,.18)",
    background: "#fff",
    color: COLORS.text,
    borderRadius: 20,
    padding: "9px 14px",
    cursor: "pointer",
    boxShadow: "0 14px 34px rgba(60,20,50,.1)",
    transition: LUXURY_TRANSITION,
  },
  currentPolishText: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    fontSize: 12,
    fontWeight: 900,
    letterSpacing: ".06em",
    textTransform: "uppercase",
    textAlign: "left",
  },
  currentPolishMeta: {
    color: COLORS.textMuted,
    fontSize: 11,
    letterSpacing: ".02em",
    textTransform: "none",
  },
  commandActions: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  },
  commandGroup: {
    position: "relative",
    display: "inline-flex",
    alignItems: "center",
  },
  commandPopover: {
    position: "fixed",
    top: 132,
    right: 18,
    zIndex: 1200,
    width: "min(320px, calc(100vw - 36px))",
    maxHeight: "calc(100vh - 154px)",
    overflow: "auto",
    display: "grid",
    gap: 8,
    padding: 12,
    border: "1px solid rgba(123,47,89,.18)",
    borderRadius: 18,
    background: "rgba(255,255,255,.98)",
    boxShadow: "0 24px 58px rgba(60,20,50,.18)",
  },
  commandPopoverWide: {
    position: "fixed",
    top: 132,
    right: 18,
    zIndex: 1200,
    width: "min(380px, calc(100vw - 36px))",
    maxHeight: "calc(100vh - 154px)",
    overflow: "auto",
    padding: 10,
    border: "1px solid rgba(123,47,89,.18)",
    borderRadius: 20,
    background: "rgba(255,255,255,.98)",
    boxShadow: "0 24px 58px rgba(60,20,50,.18)",
  },
  commandFrenchTipPopover: { position: "fixed", top: 132, left: 18,
    zIndex: 1200,
    width: "min(380px, calc(100vw - 36px))",
    maxHeight: "calc(100vh - 154px)",
    overflow: "auto",
    padding: 10,
    border: "1px solid rgba(123,47,89,.18)",
    borderRadius: 20,
    background: "rgba(255,255,255,.98)",
    boxShadow: "0 24px 58px rgba(60,20,50,.18)",
  },
  commandPolishPopover: { position: "fixed", top: 132, left: 18,
    zIndex: 1200,
    width: "min(360px, calc(100vw - 36px))",
    maxHeight: "calc(100vh - 154px)",
    overflow: "auto",
    padding: 10,
    border: "1px solid rgba(123,47,89,.18)",
    borderRadius: 20,
    background: "rgba(255,255,255,.98)",
    boxShadow: "0 24px 58px rgba(60,20,50,.18)",
  },
  commandButton: (active = false, disabled = false) => ({
    border: `1px solid ${active ? COLORS.plum : "rgba(123,47,89,.18)"}`,
    background: active ? COLORS.roseDim : "rgba(255,255,255,.88)",
    color: disabled ? COLORS.textFaint : active ? COLORS.plum : COLORS.text,
    borderRadius: 16,
    minHeight: 48,
    padding: "12px 16px",
    fontSize: 13,
    fontWeight: 900,
    cursor: disabled ? "not-allowed" : "pointer",
    opacity: disabled ? 0.55 : 1,
    boxShadow: active
      ? "0 14px 30px rgba(123,47,89,.14)"
      : "0 10px 24px rgba(60,20,50,.06)",
    transition: LUXURY_TRANSITION,
  }),
  zoomPill: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minHeight: 48,
    padding: "6px 8px",
    borderRadius: 18,
    border: "1px solid rgba(123,47,89,.18)",
    background: "#fff",
    color: COLORS.plum,
    fontWeight: 900,
    boxShadow: "0 10px 24px rgba(60,20,50,.06)",
  },
  zoomButton: {
    width: 38,
    height: 36,
    border: 0,
    borderRadius: 12,
    background: COLORS.roseDim,
    color: COLORS.plum,
    fontSize: 18,
    fontWeight: 900,
    cursor: "pointer",
    transition: LUXURY_TRANSITION,
  },
  canvasModeButton: {
    minHeight: 52,
    border: "1px solid rgba(59,31,53,.28)",
    borderRadius: 18,
    padding: "12px 18px",
    color: "#fff",
    background: "linear-gradient(135deg, #3B1F35, #7B2F59)",
    fontSize: 13,
    fontWeight: 900,
    letterSpacing: ".1em",
    textTransform: "uppercase",
    cursor: "pointer",
    boxShadow: "0 16px 34px rgba(60,20,50,.2)",
    transition: LUXURY_TRANSITION,
  },
  layout: {
    flex: 1,
    minHeight: 0,
    height: "min(100%, calc(100vh - 150px))",
    display: "grid",
    gridTemplateColumns:
      "minmax(220px, 0.9fr) minmax(320px, 1.7fr) minmax(220px, 0.85fr)",
    gap: 18,
    padding: "18px clamp(14px, 2vw, 22px)",
    overflowX: "hidden",
    overflow: "hidden",
    alignItems: "stretch",
  },
  panel: {
    background: COLORS.surface,
    border: `1px solid ${COLORS.border}`,
    borderRadius: 24,
    boxShadow: "0 18px 46px rgba(60,20,50,.08)",
    transition: "box-shadow 220ms ease, transform 220ms ease",
    minHeight: 0,
    minWidth: 0,
    overflow: "auto",
    maxHeight: "calc(100vh - 188px)",
  },
  activeStudioScroll: {
    maxHeight: "calc(100vh - 360px)",
    minHeight: 0,
    overflowY: "auto",
    overscrollBehavior: "contain",
    paddingRight: 4,
  },
  stickyPreview: {
    position: "sticky",
    top: 10,
    zIndex: 2,
    background:
      "radial-gradient(circle at 50% 10%, #fff 0%, #fff7fb 52%, #f7edf4 100%)",
    minHeight: "clamp(360px, 52vh, 560px)",
    display: "grid",
    placeItems: "center",
    overflow: "visible",
  },
  panelPad: { padding: 16 },
  sectionTitle: {
    fontSize: 12,
    letterSpacing: ".08em",
    textTransform: "uppercase",
    color: COLORS.textMuted,
    fontWeight: 800,
    marginBottom: 10,
  },
  miniButton: (active = false) => ({
    ...(active ? S.btnSecondary : S.btnGhost),
    padding: "8px 10px",
    fontSize: 12,
    borderColor: active ? COLORS.plum : COLORS.border,
    color: active ? COLORS.plum : COLORS.textMuted,
    whiteSpace: "nowrap",
  }),
  panelSection: {
    border: `1px solid ${COLORS.border}`,
    borderRadius: 16,
    marginBottom: 12,
    background: "#fff",
    overflow: "hidden",
    boxShadow: "0 10px 24px rgba(60,20,50,.05)",
    transition: "box-shadow 180ms ease, border-color 180ms ease",
  },
  panelHeader: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    padding: "10px 12px",
    border: 0,
    borderBottom: `1px solid ${COLORS.border}`,
    background: COLORS.roseDim,
    cursor: "pointer",
    transition: LUXURY_TRANSITION,
  },
  panelBody: { padding: 12, animation: "anitasetDrawerSettle 220ms cubic-bezier(.2,.8,.2,1)" },
  actionGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(42px, 1fr))",
    gap: 6,
    alignItems: "stretch",
  },
  iconOnlyButton: (active = false, disabled = false) => ({
    border: `1px solid ${active ? COLORS.plum : COLORS.border}`,
    background: active ? COLORS.roseDim : "#fff",
    color: disabled ? COLORS.textFaint : active ? COLORS.plum : COLORS.text,
    borderRadius: 10,
    padding: "7px 8px",
    minHeight: 34,
    fontSize: 15,
    fontWeight: 800,
    cursor: disabled ? "not-allowed" : "pointer",
    opacity: disabled ? 0.55 : 1,
    transition: LUXURY_TRANSITION,
  }),
  iconButton: (active = false, disabled = false) => ({
    border: `1px solid ${active ? COLORS.plum : COLORS.border}`,
    background: active ? COLORS.roseDim : "#fff",
    color: disabled ? COLORS.textFaint : active ? COLORS.plum : COLORS.text,
    borderRadius: 10,
    padding: "8px 10px",
    fontSize: 12,
    fontWeight: 700,
    cursor: disabled ? "not-allowed" : "pointer",
    opacity: disabled ? 0.55 : 1,
    transition: LUXURY_TRANSITION,
  }),
  field: { marginBottom: 14 },
  row: { display: "flex", gap: 8, alignItems: "center" },
  smallText: { fontSize: 12, color: COLORS.textMuted, lineHeight: 1.35 },
  creativeWall: { display: "grid", gap: 12, marginBottom: 14 },
  studioCard: (active = false) => ({
    display: "grid",
    gridTemplateColumns: "44px 1fr",
    gap: 12,
    alignItems: "center",
    width: "100%",
    minHeight: 88,
    padding: 14,
    border: `1px solid ${active ? COLORS.plum : "rgba(123,47,89,.16)"}`,
    borderRadius: 22,
    background: active
      ? "linear-gradient(135deg, #fff0f8, #fff)"
      : "linear-gradient(135deg, #fff, #fff8fb)",
    color: COLORS.text,
    textAlign: "left",
    cursor: "pointer",
    boxShadow: active
      ? "0 0 0 3px rgba(255,214,232,.88), 0 20px 44px rgba(123,47,89,.18)"
      : "0 12px 28px rgba(60,20,50,.07)",
    transform: active ? "translateY(-1px) scale(1.01)" : "translateY(0) scale(1)",
    transition: LUXURY_TRANSITION,
  }),
  studioCardIcon: {
    width: 44,
    height: 44,
    borderRadius: 16,
    display: "grid",
    placeItems: "center",
    background: "linear-gradient(135deg, #3B1F35, #7B2F59)",
    color: "#fff",
    fontSize: 22,
    boxShadow: "0 12px 24px rgba(60,20,50,.18)",
    transition: LUXURY_TRANSITION,
  },
  studioCardTitle: {
    display: "block",
    fontSize: 14,
    fontWeight: 900,
    letterSpacing: ".08em",
    textTransform: "uppercase",
    color: COLORS.plum,
  },
  studioCardCopy: {
    display: "block",
    marginTop: 4,
    fontSize: 12,
    lineHeight: 1.35,
    color: COLORS.textMuted,
  },
  heroCanvasPanel: {
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    overflow: "visible",
    minWidth: 0,
    border: "1px solid rgba(123,47,89,.18)",
    background: "linear-gradient(180deg, #fff 0%, #fff7fb 100%)",
    transition: "box-shadow 220ms ease, border-color 220ms ease",
  },
  heroCanvasHeader: {
    padding: "18px 22px 4px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    color: COLORS.plum,
    fontWeight: 900,
    letterSpacing: ".14em",
    textTransform: "uppercase",
  },
  nailStackHeader: {
    padding: "4px 2px 12px",
    borderBottom: "1px solid rgba(123,47,89,.12)",
    marginBottom: 12,
  },
  historyPlaceholder: {
    marginTop: 12,
    padding: 12,
    borderRadius: 16,
    border: "1px dashed rgba(123,47,89,.26)",
    background: "rgba(255,247,251,.75)",
  },
  studioDock: {
    display: "flex",
    gap: 10,
    padding: "12px 16px 16px",
    borderTop: "1px solid rgba(123,47,89,.14)",
    background: "linear-gradient(90deg, #fffaf7, #fff4fb)",
    overflowX: "auto",
  },
  dockButton: (active = false) => ({
    minHeight: 48,
    padding: "10px 16px",
    borderRadius: 16,
    border: `1px solid ${active ? COLORS.plum : "rgba(123,47,89,.16)"}`,
    background: active ? COLORS.roseDim : "#fff",
    color: active ? COLORS.plum : COLORS.textMuted,
    fontWeight: 900,
    whiteSpace: "nowrap",
    cursor: "pointer",
    transition: LUXURY_TRANSITION,
  }),
};
